// react-sample/src/components/TodoInput.js
import React, { Component } from 'react';

class Todolist extends Component {
  state = {
    context: ''
  };

  onClick = () => {
    const { context } = this.state;

    console.log(context);
  };

  render() {
    const { context } = this.state;
    return (
      <div>
        <input
          value={context}
          onChange={e => this.setState({ context: e.target.value })}
        />
        <button onClick={this.onClick}>新增</button>
      </div>
    );
  }
}

export default Todolist;

// vue-sample/src/components/TodoInput.vue
<template>
  <div>
    <input v-model="context">
    <button @click="onClick">新增</button>
  </div>
</template>

<script>
export default {
  data: function() {
    return { context: "" };
  },
  methods: {
    onClick() {
      const { context } = this;

      console.log(context);
    }
  }
};
</script>

<style scoped>
</style>
